compute_environment: "LOCAL_MACHINE"
distributed_type: "DEEPSPEED"
downcast_bf16: "no"
num_processes: 2
machine_rank: 0
main_training_function: "main"
mixed_precision: bf16
use_cpu: false

deepspeed_config:
  deepspeed_multinode_launcher: "standard"
  gradient_checkpointing: true 
  offload_optimizer_device: "none"
  offload_param_device: "none"
  zero3_init_flag: false
  zero_optimization:
    stage: 2 
    offload_optimizer:
      device: "none"
    offload_param:
      device: "none"
